<?php

use Leadpages\ServiceProviders\LeadpagesLogin;
use Pimple;

class Test_LeadpagesLogin extends WP_UnitTestCase
{

    public $app;
    public $leadpagesLogin;
    public $goodUserName;
    public $badUserName;

    public function setUp()
    {
        global $app;
        parent::setUp(); // TODO: Change the autogenerated stub

        //setup easy access to service container
        $this->app = $app;
        $this->assertInstanceOf(Pimple\Container::class, $this->app);

        //setup leadpages login object
        $this->leadpagesLogin = $this->app['leadpagesLogin'];
        $this->assertInstanceOf(LeadpagesLogin::class, $this->leadpagesLogin);

    }

    /**
     * @group login
     * @group success
     */

    public function test_get_user_token_success()
    {
        $reponse = $this->leadpagesLogin->getUserToken('brandon.braner@ave81.com', 'cd007-01');
        $this->assertEquals('success', $reponse['responseCode']);
    }

    /**
     * @group login
     * @group success
     */

    public function test_get_user_token_fail()
    {
        $reponse = $this->leadpagesLogin->getUserToken('brandon.braner@ave81.com', 'cd007-01');
        $this->assertEquals('success', $reponse['responseCode']);
    }
}