<?php

use Leadpages\ServiceProviders\LeadpagesLogin;
use Pimple;

class Test_LeadpagesLogin extends WP_UnitTestCase
{

    public $leadpagesLogin;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        //setup leadpages login object
        //remind app is setup in parent::setUp();
        $this->leadpagesLogin = $this->app['leadpagesLogin'];
        $this->assertInstanceOf(LeadpagesLogin::class, $this->leadpagesLogin);

    }

    /**
     * @group login
     * @group success
     */

    public function test_get_user_token_success()
    {
        $reponse = $this->leadpagesLogin->getUserToken($this->goodUserName, $this->goodPassword);
        $this->assertEquals('success', $reponse['responseCode']);
    }

    /**
     * @group login
     * @group success
     */

    public function test_get_user_token_fail()
    {
        $reponse = $this->leadpagesLogin->getUserToken('brandon.braner@ave81.com', 'cd007-01');
        $this->assertEquals('success', $reponse['responseCode']);
    }
}